; ============================================================
; PlatformIO Project Configuration
; Target : Seeed XIAO ESP32-S3
; Project : On-Device TinyML Vibration Classifier
; ============================================================

[env:seeed_xiao_esp32s3]
platform  = espressif32
board     = seeed_xiao_esp32s3
framework = arduino

; Serial monitor
monitor_speed = 115200

; Build flags
build_flags =
    -O2
    -DCORE_DEBUG_LEVEL=0
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    ; Uncomment the line below ONLY if PSRAM-equipped variant is used
    ; -DBOARD_HAS_PSRAM

; Library dependencies — Wire is bundled with the framework
lib_deps =

; Ensure lib/ folders are picked up
lib_extra_dirs = lib
